language: python
python:
  - "3.6"
install:
  - sudo apt-get install gfortran
  - sudo apt-get install libnetcdf-dev libnetcdff-dev
  - cd build
  - make driver
  - cd ..

script:
  - cd driver/run
  - ./taller
  