language: python
python:
  - "3.6"
install:
  - sudo apt-get install gfortran
  - sudo apt-get install libnetcdf-dev libnetcdff-dev
  - cd build
  - make driver
  - cd ../driver/run

script:
  - ./taller
  - cd ../data/outputs
  - nccmp --data --force --quiet --Tolerance=10 taller_out.nc taller_out.kgo.nc
  