# Workflow for continuous integration tests
name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        fortran-compiler: [gfortran]
    env:
      F90: ${{ matrix.fortran-compiler }}
      F90FLAGS: "-O3 -ffree-line-length-none -fcheck=bounds -finit-real=nan"
      ATOL: 0.0
      RTOL: 0.0
    # Sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    # Set up Python and install dependencies
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install python dependencies
      run: |
        conda install cartopy matplotlib netcdf4
    # Run python test
    - name: Python test
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh' 
        conda activate
        cd driver
        python test.py
    # Retrieve and expand large data files
    - name: Retrieve data files
      run: |
        GDFILE='https://docs.google.com/uc?export=download&id=17eK4_DVEvFOE9Uf6siXJDpWZJKT1aqkU'
        OUTPATH=driver/data/cosp_input.um_global.nc.gz
        curl -L -o $OUTPATH $GDFILE
        ls -lh driver/data
        gunzip ${OUTPATH}
