# Workflow for continuous integration tests
name: Continuous integration gfortran compilers
on: [push, pull_request, workflow_dispatch]

jobs:
  # This workflow contains a single job called "ci_gfortran"
  ci_gfortran:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
    # Sequence of tasks that will be executed as part of the job
    steps:
    ###############################################################################
    # Initial steps
    ###############################################################################
    # Checks-out repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v4
    - name: List dirs
      run: |
        pwd
        ls
    # Set up Python and install dependencies
    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v3.0.3
    # activate-environment: ci_env
    # environment-file: etc/environment.yml
    # python-version: ${{ matrix.python-version }}
    # auto-activate-base: false
    # auto-update-conda: true
      with:
        auto-update-conda: true
        miniforge-variant: Mambaforge
        channels: conda-forge
        python-version: ${{ matrix.python-version }}
        activate-environment: cienv
        environment-file: etc/environment.yml
        use-mamba: true
    - name: Environment info
      run: |
        conda info
    - name: Test python environment
      run: |
        cd driver
        python test.py
