# Workflow for continuous integration tests
name: Continuous integration gfortran compilers
on: [push, pull_request, workflow_dispatch]

jobs:
  # This workflow contains a single job called "ci_gfortran"
  ci_gfortran:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
    # Sequence of tasks that will be executed as part of the job
    steps:
    ###############################################################################
    # Initial steps
    ###############################################################################
    # Checks-out repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v4
    # Set up Python and install dependencies
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup conda
      # uses: s-weigand/setup-conda@v1.2.1
      # with:
      #   python-version: 3.11
      uses: conda-incubator/setup-miniconda@v3.0.3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        miniforge-variant: Mambaforge
        channels: conda-forge
        activate-environment: ci_env
        use-mamba: true
    - name: Install python packages
      run: |
        conda install --name ci_env --yes cartopy matplotlib netcdf4
    - name: Activate environment
      run: |
        conda init
        conda activate ci_env
        conda list
    - name: Test python environment
      run: |
        cd driver
        python test.py
