# Workflow for continuous integration tests
name: Continuous integration gfortran compilers
on: [push, pull_request, workflow_dispatch]

jobs:
  # This workflow contains a single job called "ci_gfortran"
  ci_gfortran:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
    # Sequence of tasks that will be executed as part of the job
    steps:
    ###############################################################################
    # Initial steps
    ###############################################################################
    # Checks-out repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v4
    - name: List dirs
      run: |
        pwd
        ls
    # Set up Python and install dependencies
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup conda environment
      # uses: s-weigand/setup-conda@v1.2.1
      # with:
      #   python-version: 3.11
      uses: conda-incubator/setup-miniconda@v3.0.3
      with:
        activate-environment: ci_env
        environment-file: etc/environment.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - name: Environment info
      run: |
        conda activate ci_env
        conda info
        conda list
    - name: Test python environment
      run: |
        cd driver
        python test.py
