# Workflow for continuous integration tests
name: Continuous integration gfortran compilers
on: [push, pull_request, workflow_dispatch]

jobs:
  # This workflow contains a single job called "ci_gfortran"
  ci_gfortran:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
    # Sequence of tasks that will be executed as part of the job
    defaults:
      run:
        shell: bash -el {0}
    env:
      GDKGO1: https://docs.google.com/uc?export=download&id=11dKcIL3EQr7s6jbo4f9GsoW0SufesGbq
      GDKGO2: https://docs.google.com/uc?export=download&id=1s5Ha6Hqnv_hWbRUs8KQpJ4Lxy8uvJDar
      GDKGO3: https://docs.google.com/uc?export=download&id=1kY1lRgzd0UhDiQef2u-VgTQql_iut3U2
    steps:
    ###############################################################################
    # Initial steps
    ###############################################################################
    # Checks-out repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v4
    - name: List dirs
      run: |
        pwd
        ls
    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v3.0.3
      with:
        auto-update-conda: true
        activate-environment: cienv
        environment-file: etc/environment.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - name: Environment info
      run: |
        conda info
    ###############################################################################
    # Retrieve files and run tests
    ###############################################################################
    - name: Retrieve input files
      run: |
        cd ${GITHUB_WORKSPACE}
        OUTPATH=driver/data/outputs/kgo.nc.gz
        curl -sSfL -o $OUTPATH $GDKGO1
        gunzip ${OUTPATH}
        cd driver/data/outputs
        ls -l
    - name: Test python environment
      run: |
        cd driver
        python test.py
