# Workflow for continuous integration tests
name: CI
on: [push, pull_request]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    env:
      F90: gfortran-8

    # Sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python_requirements.txt
    - name: Install gfortran and netCDF libraries
      run: |
        sudo apt-get install ${F90}
        sudo apt-get install libnetcdf-dev
        ${F90} --version
    - name: Build and install netCDF Fortran library
      run: |
        NCFF=${HOME}/netcdff
        git clone https://github.com/Unidata/netcdf-fortran.git --branch v4.4.4
        cd netcdf-fortran
        ./configure --prefix=${NCFF}
        make
        make install
    - name: Build driver
      run: |
        cd build
        make driver
    - name: Run test
      run: |
        NCFF=${HOME}/netcdff
        LD_LIBRARY_PATH+=:${NCFF}/lib
        echo ${LD_LIBRARY_PATH}
        ls ${NCFF}
        cd driver/run
        ./taller
    - name: Compare output against KGO
      run: |
        cd driver
        python cosp2_test_01.py data/outputs/taller_out.kgo.nc data/outputs/taller_out.nc --atol=0.0 --rtol=0.0
    - name: Upload output file if test fails
      if: failure()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: taller_out.nc
        path: driver/data/outputs/taller_out.nc
