# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ travis_tests ]
  pull_request:
    branches: [ travis_tests ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python_requirements.txt
    - name: Install gfortran and netCDF libraries
      run: |
        sudo apt-get install gfortran
        sudo apt-get install libnetcdf-dev libnetcdff-dev
    - name: Build driver
      run: |
        cd build
        make driver
    - name: Run test
      run: |
        cd driver/run
        ./taller
    - name: Compare output against KGO
      run: |
        cd driver
        python cosp2_test_01.py data/outputs/taller_out.kgo.nc data/outputs/taller_out.nc
    - name: Upload output file
      uses: actions/upload-artifact@v1.0.0
      with:
        name: taller_out.nc
        path: driver/data/outputs
